# Base Info
url: 'https://ltrobotics.org'
title: 'LT Robotics'
description: 'Robotics Club at Lake Travis High School'
loc: 'Austin, Texas'
year: '2023'
# Social Media
github: 'ltrobotics'
email: 'ltrobotics78738@gmail.com'
lths: 'https://ltisdschools.org/lths'
ltisd: 'https://ltisdschools.org'
ltinsta: 'instagram.com/lthsrobotics/?next+%2F'

# Blog(future deployment)
permalink: 'blog/:title'
